function [E, H2E] = hex2edge(H)
    Eall = [H(:,1),H(:,2);...
        H(:,2),H(:,3); ...
        H(:,3),H(:,4); ...
        H(:,4),H(:,1); ...
        H(:,5),H(:,1); ...
        H(:,8),H(:,5); ...
        H(:,4),H(:,8); ...
        H(:,6),H(:,5); ...
        H(:,7),H(:,6); ...
        H(:,7),H(:,8); ...
        H(:,3),H(:,7); ...
        H(:,2),H(:,6)];
    
    
    [~,ia,ic] = unique(sort(Eall,2),'rows');
    E = Eall(ia,:);
    nH = size(H,1);
    nE = size(E,1);
    
    einds = repmat(1:nE,1,2);
    heinds = reshape(einds(ic),[],12);
    H2E = sparse(repmat(1:nH,1,12), heinds, heinds*0+1, nH, nE);
end